FROM node:10.5.0

WORKDIR /data/freelog-resource-provider

COPY . /data/freelog-resource-provider

ENV NODE_ENV prod \
    EGG_SERVER_ENV prod \
    PORT 7001 \
    TZ=Asia/Shanghai \

RUN npm install /data/freelog-resource-provider && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

EXPOSE 7001

CMD [ "npm", "start" ]
