FROM node:10.5.0

MAINTAINER yuliang <yuliang@ciwong.com>

RUN mkdir -p /data/freelog-resource-provider

WORKDIR /data/freelog-resource-provider

COPY . /data/freelog-resource-provider

RUN npm install

ENV NODE_ENV prod
ENV EGG_SERVER_ENV prod
ENV PORT 7101
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

EXPOSE 7101

CMD [ "npm", "start" ]
