FROM daocloud.io/node:8.5-alpine

MAINTAINER yuliang <yuliang@ciwong.com>

RUN mkdir -p /data/freelog-resource-provider

WORKDIR /data/freelog-resource-provider

COPY . /data/freelog-resource-provider

RUN npm install

ENV NODE_ENV test
ENV EGG_SERVER_ENV test
ENV PORT 5001

EXPOSE 5001

CMD [ "npm", "start" ]
